[DEBUG] [2020-11-20 07:13:00,804] [20527:139871606757184] - pool.py[line:129]: No connection available in pool.
[DEBUG] [2020-11-20 07:13:00,838] [20527:139871606757184] - pool.py[line:158]: Created new connection 139871324953288.
[DEBUG] [2020-11-20 07:13:00,857] [20527:139871606757184] - peewee.py[line:2863]: ('SELECT `t1`.`f_create_date`, `t1`.`f_update_date`, `t1`.`f_name`, `t1`.`f_namespace`, `t1`.`f_address`, `t1`.`f_engine`, `t1`.`f_type`, `t1`.`f_options`, `t1`.`f_partitions`, `t1`.`f_id_delimiter`, `t1`.`f_in_serialized`, `t1`.`f_have_head`, `t1`.`f_schema`, `t1`.`f_count`, `t1`.`f_part_of_data`, `t1`.`f_description`, `t1`.`f_create_time`, `t1`.`f_update_time` FROM `t_storage_table_meta` AS `t1` WHERE ((`t1`.`f_name` = %s) AND (`t1`.`f_namespace` = %s))', ['b9cac0762aff11eba0823ea3df35c0a6', 'output_data_202011200707112994524_intersection_0_0'])
[DEBUG] [2020-11-20 07:13:00,874] [20527:139871606757184] - pool.py[line:185]: Returning 139871324953288 to pool.
[DEBUG] [2020-11-20 07:13:01,443] [20527:139871606757184] - peewee.py[line:2863]: ('SELECT `t1`.`f_create_date`, `t1`.`f_update_date`, `t1`.`f_name`, `t1`.`f_namespace`, `t1`.`f_address`, `t1`.`f_engine`, `t1`.`f_type`, `t1`.`f_options`, `t1`.`f_partitions`, `t1`.`f_id_delimiter`, `t1`.`f_in_serialized`, `t1`.`f_have_head`, `t1`.`f_schema`, `t1`.`f_count`, `t1`.`f_part_of_data`, `t1`.`f_description`, `t1`.`f_create_time`, `t1`.`f_update_time` FROM `t_storage_table_meta` AS `t1` WHERE ((`t1`.`f_name` = %s) AND (`t1`.`f_namespace` = %s))', ['96be3f402aff11eb99d93ea3df35c0a6', 'output_data_202011200707112994524_intersection_1_0'])
[DEBUG] [2020-11-20 07:13:01,459] [20527:139871606757184] - pool.py[line:185]: Returning 139871324953288 to pool.
